hparams = {
    'scale':'demo',
    'mode':'train',
    'batch_size':10,
    'title_size':20,
    'abs_size':40,
    'his_size':50,
    'npratio':4,
    'dropout_p':0.2,
    'query_dim':200,
    'embedding_dim':300,
    'filter_num':150,
    'value_dim':16,
    'head_num':16,
    'epochs':8,
    'metrics':'auc,mean_mrr,ndcg@5,ndcg@10',
    'device':'cpu',
    'attrs': ['title'],
    'k':0,
    'select':None,
    'save_step':[0],
    'news_id':False,
    'validate':False,
    'interval':10,
    'spadam':True
}